# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  latest: latest
  buildtag: '$(Build.BuildNumber)'

stages:
  - stage: build
    variables:
      basetag: 'harnoorpuniyani/todo-threetier-backend'
    pool:
      vmImage: ubuntu-latest
    displayName: Build Backend
    jobs:
      - job:
        strategy:
          matrix: 
            linux:
              OS: ubuntu-latest
              platformOs: linux
            windows:
              OS: windows-latest
              platformOs: windows
          maxParallel: 2
        steps:
         - task: DockerInstaller@0
           inputs:
            dockerVersion: '28.3.0'
         - script: docker buildx version
           displayName: Check docker buildx
         - task: Docker@2
           inputs:
            containerRegistry: 'docker-harnoorpuniyani'
            command: 'login'
            addPipelineData: false
            addBaseImageData: false
         
         - script: |
            docker buildx create --use --name builder
           displayName: create Buildx Builder
         
         - script: |
            cd backend-todo/ && docker buildx build --platform $(platformOs)/amd64,$(platformOs)/arm64 -t '$(basetag):$(buildtag)-$(platformOs)' -t '$(basetag):$(latesttag)-$(platformOs)' . --push
           displayName: Create and Push Multi Architecture Image - $(platformOs)
