# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- azure-pipelines

pool:
  vmImage: ubuntu-latest

variables:
  latesttag: latest
  buildtag: '$(Build.BuildNumber)'

stages:
  - stage: build
    displayName: Build Images
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job:
        displayName: Build Backend
        variables:
          basetag: 'harnoorpuniyani/todo-threetier-backend'
        strategy:
          matrix: 
            linux:
              OS: ubuntu-latest
              platformOs: linux
            # windows:
            #   OS: windows-latest
            #   platformOs: windows
          maxParallel: 2
        steps:
         - task: DockerInstaller@0
           inputs:
            dockerVersion: '28.3.0'
         - script: docker buildx version
           displayName: Check docker buildx
         - task: Docker@2
           inputs:
            containerRegistry: 'docker-harnoorpuniyani'
            command: 'login'
            addPipelineData: false
            addBaseImageData: false
         
         - script: |
            docker buildx create --use --name builder
           displayName: create Buildx Builder
         
         - script: |
            cd backend-todo/ && docker buildx build --platform $(platformOs)/amd64,$(platformOs)/arm64 -t '$(basetag):$(buildtag)-$(platformOs)' -t '$(basetag):$(latesttag)-$(platformOs)' . --push
           displayName: Create and Push Multi Architecture Image - $(platformOs)
      - job:
        displayName: Build Frontend
        variables:
          basetag: 'harnoorpuniyani/todo-threetier-frontend'
        strategy:
          matrix:
            lin:
              OS: ubuntu-latest
              platformOs: linux
          maxParallel: 1
        steps:
         - task: DockerInstaller@0
           inputs:
            dockerVersion: '28.3.0'
         - script: docker buildx version
           displayName: Check docker buildx
         - task: Docker@2
           inputs:
            containerRegistry: 'docker-harnoorpuniyani'
            command: 'login'
            addPipelineData: false
            addBaseImageData: false
         
         - script: |
            docker buildx create --use --name builder
           displayName: create Buildx Builder
         
         - script: |
            cd frontend-todo/ && docker buildx build --platform $(platformOs)/amd64,$(platformOs)/arm64 -t '$(basetag):$(buildtag)-$(platformOs)' -t '$(basetag):$(latesttag)-$(platformOs)' . --push
           displayName: Create and Push Multi Architecture Image - $(platformOs)
  - stage: Test
    displayName: Unit Testing
    dependsOn: build
    condition: succeeded('build')
    jobs:
      - job: Backend
        variables:
          basetag: 'harnoorpuniyani/todo-threetier-backend'
        pool:
         vmImage: ubuntu-latest 
        displayName: Testing Backend
        strategy:
          matrix:
            linux:
              os: ubuntu-latest
              platformOs: linux
        steps:
          - script: |
              docker run --name redisdb -p 6379:6379 -d redis/redis-stack-server:latest
            displayName: Run Refis

          - script: |
              docker run --name backend --rm -p 5000:5000 $(basetag):$(buildtag)-$(platformOs) npm test
            displayName: Runing Test cases
  - stage: Deploy
    condition: succeeded()
    dependsOn: Test
    jobs:
      - deployment: 
        environment: Dev
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "hello deployment"
                  displayName: Sample deploy


