# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- azure-pipelines

pool:
  vmImage: ubuntu-latest

variables:
  latesttag: latest
  buildtag: '$(Build.BuildNumber)'

parameters:
  - name: buildImages
    type: boolean
    displayName: Build Images
    default: false
  - name: testChanges
    type: boolean
    displayName: Test Changes
    default: true
  - name: deployment
    type: boolean
    displayName: deploy changes
    default: true

stages:
  - stage: Code
    displayName: code analysis
    jobs:
    - job: Frontend
      displayName: Static code analysis Frontend
      steps:
        - task: SonarCloudPrepare@3
          inputs:
            SonarQube: 'sonar qube cloud service connection'
            organization: 'arzom-test'
            scannerMode: 'cli'
            configMode: 'manual'
            cliProjectKey: 'arzom-test_test-todo'
            cliProjectName: 'Test-todo'
            cliSources: '.'
            extraProperties: |
              sonar.projectKey=arzom-test_test-todo
              sonar.organization=arzom-test
        - script: |
            cd frontend-todo && \
            npm install && \
            npm run build
        - task: SonarCloudAnalyze@3
          inputs:
            jdkversion: 'JAVA_HOME_21_X64'
        - task: SonarCloudPublish@3
          inputs:
            pollingTimeoutSec: '300'
  - stage: build
    dependsOn: Code
    displayName: Build Images
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: build
        displayName: Build Backend
        condition: eq('${{parameters.buildImages}}',true)
        variables:
          basetag: 'harnoorpuniyani/todo-threetier-backend'
        strategy:
          matrix: 
            linux:
              OS: ubuntu-latest
              platformOs: linux
            # windows:
            #   OS: windows-latest
            #   platformOs: windows
          maxParallel: 2
        steps:
         - task: DockerInstaller@0
           inputs:
            dockerVersion: '28.3.0'
         - script: docker buildx version
           displayName: Check docker buildx
         - task: Docker@2
           inputs:
            containerRegistry: 'docker-harnoorpuniyani'
            command: 'login'
            addPipelineData: false
            addBaseImageData: false
         
         - script: |
            docker buildx create --use --name builder
           displayName: create Buildx Builder
         
         - script: |
            cd backend-todo/ && docker buildx build --platform $(platformOs)/amd64,$(platformOs)/arm64 -t '$(basetag):$(buildtag)-$(platformOs)' -t '$(basetag):$(latesttag)-$(platformOs)' . --push
           displayName: Create and Push Multi Architecture Image - $(platformOs)
      - job:
        displayName: Build Frontend
        variables:
          basetag: 'harnoorpuniyani/todo-threetier-frontend'
        strategy:
          matrix:
            lin:
              OS: ubuntu-latest
              platformOs: linux
          maxParallel: 1
        steps:
         - task: DockerInstaller@0
           inputs:
            dockerVersion: '28.3.0'
         - script: docker buildx version
           displayName: Check docker buildx
         - task: Docker@2
           inputs:
            containerRegistry: 'docker-harnoorpuniyani'
            command: 'login'
            addPipelineData: false
            addBaseImageData: false
         
         - script: |
            docker buildx create --use --name builder
           displayName: create Buildx Builder
         
         - script: |
            cd frontend-todo/ && docker buildx build --platform $(platformOs)/amd64,$(platformOs)/arm64 -t '$(basetag):$(buildtag)-$(platformOs)' -t '$(basetag):$(latesttag)-$(platformOs)' . --push
           displayName: Create and Push Multi Architecture Image - $(platformOs)
  - stage: Test
    displayName: Unit Testing
    dependsOn: build
    condition: or(succeeded('build'),eq('${{parameters.testChanges}}',true))
    jobs:
      - job: Backend
        variables:
          basetag: 'harnoorpuniyani/todo-threetier-backend'
        pool:
         vmImage: ubuntu-latest 
        displayName: Testing Backend
        strategy:
          matrix:
            linux:
              os: ubuntu-latest
              platformOs: linux
        steps:
          - script: |
              docker network create --driver bridge todo
            displayName: Setting up Docker Network
          - script: |
              docker run --name redisdb -p 6379:6379 -d --network todo redis/redis-stack-server:latest
            displayName: Run Redis

          - script: |
              docker run --name backend --rm -p 5000:5000 -e REDIS_HOST=redisdb --network todo $(basetag):$(latesttag)-$(platformOs) npm test
            displayName: Runing Test cases

  - stage: Deploy
    condition: or(succeeded(),eq('${{parameters.deployment}}',true))
    dependsOn: Test
    jobs:
      - deployment: 
        displayName: Deployment Job
        environment: Dev
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "hello deployment"
                  displayName: Sample deploy


