apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.frontend.name }}
    labels:
    {{ range $key, $val := .Values.frontend.labels }}
        {{$key}}: {{$val}}
    {{end}}
spec:
    replicas: {{ .Values.frontend.replicas }}
    selector:
        matchLabels:
        {{ range $key,$val := .Values.frontend.podLabels }}
            {{$key}}: {{$val}}
        {{end}}
    template:
        metadata:
            name: frontend-template-name
            labels:
            {{ range $key,$val := .Values.frontend.podLabels }}
                {{$key}}: {{$val}}
            {{end}}
        spec:
            containers:
                - name: {{ "frontend-PodName" | lower }}
                  image: {{ .Values.frontend.image.name }}:{{ .Values.frontend.image.tag }}
                  imagePullPolicy: {{ .Values.global.imagePullPolicy}}
                  resources:
                    requests:
                        cpu: {{ .Values.frontend.resources.requests.cpu }}
                        memory: {{ .Values.frontend.resources.requests.memory }}
                    limits:
                        cpu: {{ .Values.frontend.resources.limits.cpu }}
                        memory: {{ .Values.frontend.resources.limits.memory }}
                  {{ if .Values.frontend.volumes.enabled }}
                  volumeMounts:
                    - name: {{ .Values.frontend.volumes.name }}
                      mountPath: {{ .Values.frontend.volumes.path }}
                      subPath: {{ .Values.frontend.volumes.subPath}}
                  {{end }}
                  ports:
                    - containerPort: {{ .Values.frontend.podPort}}
            volumes:
                - name: {{ .Values.frontend.volumes.name }}
                  configMap:
                    name: {{ .Values.frontend.volumes.configmapDetails.name }}
                    items:
                    {{range $i, $val := .Values.frontend.volumes.configmapDetails.items }}
                        - key: {{$val.key}}
                          path: {{$val.path}}
                    {{ end }}
