apiVersion: apps/v1
kind: Deployment
metadata:
  name: backkend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-pod
    spec:
      containers:
      - name: backend
        image: harnoorpuniyani/todo-threetier-backend:20250723.14-linux
        imagePullPolicy: IfNotPresent
        restartPolicy: Always
        env:
          - name: REDIS_HOST
            value: redis-service
        resources:
          requests:
            memory: 64Mi
            cpu: 250m
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /tasks
            port: 5000
            host: localhost
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /tasks
            port: 5000
            host: localhost
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        ports:
        - containerPort: 5000
