apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-pod
    spec:
      containers:
      - name: frontend
        image: harnoorpuniyani/todo-threetier-frontend:20250723.14-linux
        imagePullPolicy: IfNotPresent
        restartPolicy: Always
        resources:
          requests:
            memory: 64Mi
            cpu: 250m
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
            host: localhost
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
            host: localhost
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        volumeMounts:
          - name: configvolume
            mountPath: /build/envmount
            subPath: env.js
        ports:
        - containerPort: 3000
      volumes:
        - name: configvolume
          configMap:
            name: env.js
            items:
              - key: window.env
                path: env.js