apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisdb
  template:
    metadata:
      name: redisdb
      labels:
        app: redisdb
    spec:
      containers:
        - name: redisdb
          image: redis/redis-stack-server:latest
          imagePullPolicy: IfNotPresent
          restartPolicy: Always
          readinessProbe:
            tcpSocket:
              host: localhost
              port: 6379
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            exec:
              command:
                - redis-cli
                - PING
          volumeMounts:
            - name: redis-storage
              mountPath: /data
          resources:
            requests:
              cpu: 500m
              memory: 200Mi
            limits:
              cpu: 800m
              memory: 500Mi
          ports:
            - containerPort: 6379
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redispvc
      