apiVersion: v1
kind: PersistentVolume
metadata:
  name: redispv
  labels:
    type: local
spec:
  capacity:
    storage: 600Mi
  volumeMode: Filesystem
  accessModes:
    - ReadwriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  local:
    path: /mnt/disks/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchFields:
            - key: disk
              operator: In
              values:
                - local
  