apiVersion: v1
kind: PersistentVolumeClaim
metadata:
	name: redis-pvc
spec:
	storageClassName: {{.Values.pvc.storageClassName}}
	accessModes:
		- ReadWriteOnce
	resources:
		requests:
			storage: 5Gi
